mbaas:
  key: ""
  hostname: ""
  username: ""
  password: ""
pubsub:
  key: ""
  secret: ""
  hostname: ""
platform:
  hostname: ""
logging:
  level: "INFO"
  loggers:
    com.axway: "DEBUG"
server:
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: 0.0.0.0
  adminConnectors:
    - type: http
      port: 8081
      bindHost: 0.0.0.0
entitlements:
  uri: ""
  org: ""
axway_id:
  client_id: ""
  client_secret: ""
  uri: "https://login-preprod.axway.com"
  realm: "Broker"
