axway_id:
  uri: ""
  realm: ""
  client_id: ""
  client_secret: ""
entitlements:
  uri: ""
  org: ""
mbaas:
  key: ""
  hostname: ""
  username: ""
  password: ""
pubsub:
  key: ""
  secret: ""
  hostname: ""
platform:
  hostname: ""
logging:
  level: "INFO"
  loggers:
    com.axway: "DEBUG"
